name: Deploy Ngx Workshop BFF

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Copy to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: '.'
          target: '/opt/ngx-nestjs-services/ngx-workshop-bff'

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/ngx-nestjs-services/ngx-workshop-bff

            echo "🔑 Writing .env from GitHub secrets..."
            echo "PORT=${{ secrets.PORT }}" > .env
            echo "AUTH_BASE_URL=${{ secrets.AUTH_BASE_URL }}" >> .env
            echo "MFE_ORCHESTRATOR_URL=${{ secrets.MFE_ORCHESTRATOR_URL }}" >> .env

            echo "🚀 Building and starting container..."
            docker build -t ngx-workshop-bff .
            docker stop ngx-workshop-bff || true
            docker rm ngx-workshop-bff || true
            docker run -d --name ngx-workshop-bff --env-file .env -p 3002:3002 ngx-workshop-bff
